### PR TITLE
fix to work with RN0.26

### PR DESCRIPTION
**Pull request by aksonov**
fix to work with RN0.26

### CODE REVIEW

**Comment by JeanLebrument** [comment]
Thanks for your contribution!

**Comment by aksonov** [comment]
Thank you for merge, when it will be published to npm?

**Comment by JeanLebrument** [comment]
I will right now! On Mon, May 23, 2016 at 11:59 AM Pavel Aksonov notifications@github.com
wrote:
Thank you for merge, when it will be published to npm?

**Comment by aksonov** [comment]
thanks! i've got other problem - i don't see userID, phoneNumber as 'response' param. Previous versions (1.0.5) returned it, were they removed?

**Pull request merged**
