### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kb**
Update the npm install value to install the npm hosted package from https://www.npmjs.com/package/react-native-fabric-digits

### CODE REVIEW

**Comment by JeanLebrument** [comment]
Hello @kb thanks for the PR.

Could give me more informations about it?

**Comment by kb** [comment]
I don't use npm often but I believe the current installation command of `npm install proximaio/react-native-fabric-digits --save` will install the module from this [github repository](https://github.com/proximaio/react-native-fabric-digits), which I do not believe to be what you want for this particular fork of the code. Instead the install instructions should point to the [npm module](https://www.npmjs.com/package/react-native-fabric-digits) you've appeared to push under your npm username.

In general do you intend to maintain this fork of the code? I have some other changes in the works, so if not I'll maintain my own fork of changes.

**Comment by JeanLebrument** [comment]
Yes I intend to maintain this fork of the code. Feel free to propose contribution to this repository. I will merge pull requests after reviewing them and update the package on npm.

**Comment by kb** [comment]
Okay. Could you please elaborate why you decided to not merge this change? Is my understanding of the source for the npm installation for the source from this repository not correct?

**Comment by JeanLebrument** [comment]
Rather having multiple versions of a single project in multiple GitHub / NPM repositories, it's smarter to contribute to a single repo (by sending pull requests) and I will pay attention to update the NPM repository. Does that sound good to you?

**Pull request closed without merging**
