### PR TITLE
Fix broken Logout button and bring back getSessionDetails to login button

### PR DESCRIPTION
**Pull request by EmilScherdin**
In release 1.0.14 the logout button broke and the getSessionDetails function was removed from the login button. Seems a bit wrong to not have the getSessionDetails function on the login button so i added it again.
## Fixed 
- Logout button now works again
- Brings back getSessionDetails to login button
## New
- Add highlight color prop on buttons. (So buttons can be other color than black when pressing)

🎉🍿

### CODE REVIEW

**Comment by jpdriver** [comment]
hmm not sure i agree.. when you haven't logged in yet (i.e. and you're rendering LogInButton) you won't have sessionDetails yet so it will just return null...

i was the one who put it there originally so this is all my bad; but i think i might have been testing only with a single button not with separate LogIn and LogOut ones.

conceptually though, what's the scenario where you need to try and get the sessionDetails before the user has actually gone through the flow and created the session? to me, feels like that should only exist on the LogOut one -- which is why i changed it..

apologies if this has broken things for you! 😰

**Comment by EmilScherdin** [comment]
I agree that it's not a perfect place to have getSessionDetails on the login button. But i don't think having it on the logout button is a better option...

My scenario is that i have the only the login button in one view and after they have logged in I want to get the UserID and phone number from session details. Can I get the session details without rendering the logout button because it feels strange to render a hidden logout button just to get the details, don't you think? @jpdriver

**Comment by JeanLebrument** [comment]
@jpdriver Curious to have your feedback on this one.

**Comment by JeanLebrument** [comment]
Thanks for your contribution!

**Pull request merged**
